#!/bin/bash

set -exo pipefail

# run bedrock tests against the prod domain

function setK8sConfig() {
    export KUBECONFIG="${HOME}/.kube/${1}.kubeconfig"
}

BASE_URL="https://www.mozilla.org"
CLUSTERS=(
    "oregon-b"
    "frankfurt"
    "tokyo"
)

for cluster in "${CLUSTERS[@]}"; do
    setK8sConfig $cluster
    kubectl run bedrock-prod-cdn-test \
                --attach --rm \
                --image mozorg/bedrock_test:latest \
                --env "BASE_URL=${BASE_URL}" \
                --env "MARK_EXPRESSION=headless" \
                --env "PYTEST_PROCESSES=5" \
                --command -- bin/run-integration-tests.sh
done
