#!/bin/bash

# run bedrock tests against the prod domain

function setK8sRegion() {
    export KUBECONFIG="${HOME}/.kube/${1}.kubeconfig"
}

set -exo pipefail

BASE_URL="https://www.mozilla.org"
REGIONS=( oregon-b frankfurt tokyo )

for region in $REGIONS; do
    setK8sRegion $region
    kubectl run bedrock-prod-cdn-test \
                --attach --rm \
                --image mozorg/bedrock_test:latest \
                --env "BASE_URL=${BASE_URL}" \
                --env "MARK_EXPRESSION=headless" \
                --env "PYTEST_PROCESSES=5" \
                --command -- bin/run-integration-tests.sh
    echo "Exit code: $?"
    echo "Config: $KUBECONFIG"
done
